# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code quality

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run code quality report with radon
      run: |
        radon cc -s -e "*test*" soil_moisture_sensor
        radon mi -s -e "*test*" soil_moisture_sensor
        radon raw -s -e "*test*" soil_moisture_sensor 
    - name: Test with pytest
      run: |
        coverage run -m pytest
    - name: Test Coverage Report
      run: |
        coverage report -m
